{% set name = "ennemi" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ennemi-{{ version }}.tar.gz
  #sha256: 4658e7a70eabeda050d6710bff49f65397570874d8525b8aec342a249c9cb671
  url: https://github.com/polsys/ennemi/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0c84a28cc2477060600de0b428c940df2c1ee396c0501d09985f2b6874a37102

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy >=1.23
    - scipy >=1.9,<2.dev0

test:
  imports:
    - ennemi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://polsys.github.io/ennemi/
  summary: Non-linear correlation detection with mutual information
  dev_url: https://github.com/polsys/ennemi/
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - camaramm
